#!/usr/bin/env bash

arr=("$@")

init_viewer(){
    echo Init viewer
    mkdir -p viewer/__viewer_cache__
    touch viewer/__viewer_cache__/cmp_exp
    touch viewer/__viewer_cache__/out.txt
}

init_example(){
    echo Init example
    ./scripts/skeleton.py
}

val_in_arr(){
    values=("$@")
    for parm in "${arr[@]}"; do
        for value in "${values[@]}"; do
            if [[ $parm == $value ]]
            then
                return 0
            fi
        done
    done
    return 1
}

run(){
    val_in_arr 'i' 'interactive'; interactive=$?
    val_in_arr 'd' 'developer'; developer=$?

    if [ $interactive -eq 0 ] ; then
        echo Running in interactive mode
        init_viewer &&
            init_example &&
            python3 viewer/viewer.py "${arr[@]}" &
        PID=$!
        tmux split-window -h "vim viewer/__viewer_cache__/example.cpp"
        vim -n -S "scripts/cmds.vim" -R -M -o viewer/__viewer_cache__/cmp_exp viewer/__viewer_cache__/out.txt &&
            ./scripts/clean.sh $PID
    elif [ $developer -eq 0 ]; then
        echo Running in developer mode
        init_viewer &&
            python3 viewer/viewer.py "${arr[@]}" &
        PID=$!
        vim -n -S "scripts/cmds.vim" -R -M -o viewer/__viewer_cache__/cmp_exp viewer/__viewer_cache__/out.txt &&
            ./scripts/clean.sh $PID
    else
        python3 viewer/viewer.py "${arr[@]}"
    fi
}

run
