#!/usr/bin/env bash

arr=("$@")

function call_help(){
    ./viewer/viewer.py -h
}

function init_viewer(){
    echo Init viewer
    mkdir -p viewer/__viewer_cache__
    touch viewer/__viewer_cache__/cmp_exp
    touch viewer/__viewer_cache__/out.txt
}

function init_example(){
    echo Init example
    ./scripts/skeleton.py
}

function run(){
    shopt -s nocasematch
    for i in "${arr[@]}"
    do
       PARM=`echo $i | awk -F= '{print $1}'`
       if [[ $PARM == '-h' ]]
       then
          call_help
          exit
       elif [[ $PARM == 'i' ]] || [[ $PARM == 'interactive' ]]
       then
           echo Running in interactive mode
           init_viewer &&
           init_example &&
           ./viewer/viewer.py "${arr[@]}" &
           tmux split-window -h "vim viewer/__viewer_cache__/example.cpp"
           vim -n -S "scripts/cmds.vim" -R -M -o viewer/__viewer_cache__/cmp_exp viewer/__viewer_cache__/out.txt &&
           ./scripts/clean.sh
           exit
       elif [[ $PARM == 'd' ]] || [[ $PARM == 'developer' ]] ||  [[ $PARM == '-c' ]] || [[ $PARM == '--config' ]]
       then
           echo Running in developer mode
           init_viewer &&
           ./viewer/viewer.py "${arr[@]}" &
           vim -n -S "scripts/cmds.vim" -R -M -o viewer/__viewer_cache__/cmp_exp &&
           ./scripts/clean.sh
           exit
       fi
    done

    echo Error: mode not found try I or D or -h
    exit 1
}

run
