#!/usr/bin/env bash

touch viewer/__viewer_cache__/cmp_exp &&
cd viewer/ &&
./viewer.py "$@" &
vim -n -S "scripts/cmds.vim" -R -M -o viewer/__viewer_cache__/cmp_exp &&
./scripts/clean.sh &&
rm viewer/__viewer_cache__/cmp_exp
